language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk8
    - rvm: 2.1.1
      jdk: openjdk6
    - rvm: 2.1.1
      jdk: oraclejdk7
    - rvm: 2.1.1
      jdk: oraclejdk8
    - rvm: 2.1.2
      jdk: openjdk6
    - rvm: 2.1.2
      jdk: oraclejdk7
    - rvm: 2.1.2
      jdk: oraclejdk8
addons:
  code_climate:
    repo_token: 323644d852f6ba54213f25446d6f4276dbec0adb74fefce770b083cd3e83ea1e