language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - jruby
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk8
    - rvm: 2.1.1
      jdk: openjdk6
    - rvm: 2.1.1
      jdk: oraclejdk7
    - rvm: 2.1.1
      jdk: oraclejdk8
    - rvm: 2.1.2
      jdk: openjdk6
    - rvm: 2.1.2
      jdk: oraclejdk7
    - rvm: 2.1.2
      jdk: oraclejdk8
    - rvm: 2.1.3
      jdk: openjdk6
    - rvm: 2.1.3
      jdk: oraclejdk7
    - rvm: 2.1.3
      jdk: oraclejdk8
    - rvm: 2.1.4
      jdk: openjdk6
    - rvm: 2.1.4
      jdk: oraclejdk7
    - rvm: 2.1.4
      jdk: oraclejdk8
    - rvm: 2.1.5
      jdk: openjdk6
    - rvm: 2.1.5
      jdk: oraclejdk7
    - rvm: 2.1.5
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 56e2763b5bfe138f566c5f2bf23c14deee4f8990324436dbde07ee2a34bb87f8